---
# tasks file for mysql
- name: be sure mysql-server is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - MySQL-python27
  tags: mysqld

- name: be sure mysqld is running and enabled
  service:
    name: mysqld
    state: running
    enabled: yes
  tags: mysqld

- name: Create database
  mysql_db:
    name: "{{ dbname }}"
    state: present
    encoding: utf8
  tags: mysqld

- name: Create database user
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    priv: "{{ dbname }}.*:ALL"
    state: present
  tags: mysqld
